### PR TITLE
Fix typos in docs and comments

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
This PR aims to fix typos in the docs and comments.

@michaelgrund should your KIT email address be replaced by the link to the `sws_tools` GitHub repository and/or your ORCID?

### CODE REVIEW

**Comment by michaelgrund** [comment]
> This PR aims to fix typos in the docs and comments.
> 
> @michaelgrund should your KIT email address be replaced by the link to the `sws_tools` GitHub repository and/or your ORCID?

That would be nice @yvonnefroehlich :wink: .

**Comment by yvonnefroehlich** [comment]
> > This PR aims to fix typos in the docs and comments.
> > @michaelgrund should your KIT email address be replaced by the link to the `sws_tools` GitHub repository and/or your ORCID?
> 
> That would be nice @yvonnefroehlich 😉 .

Sure, happy to help (a bit) 🙂.
I changed all occurrences. However, there are some files which do not contain any reference:
- [`plot_arc3D.m`](https://github.com/michaelgrund/sws_tools/blob/main/01_stereoplots/plot_arc3D.m)
- [`SWS_Analysis_BASICS_check_matlab_version.m`](https://github.com/michaelgrund/sws_tools/blob/main/01_stereoplots/SWS_Analysis_BASICS_check_matlab_version.m)
- [`SWS_modeling_check_matlab_version.m`](https://github.com/michaelgrund/sws_tools/blob/main/01_stereoplots/SWS_Analysis_BASICS_check_matlab_version.m)
- [`SWS_modeling_precomp_single_layer.m`](https://github.com/michaelgrund/sws_tools/blob/main/03_modeling/SWS_modeling_precomp_single_layer.m)
- [`SWS_modeling_calc_dipping.m`](https://github.com/michaelgrund/sws_tools/blob/main/03_modeling/SWS_modeling_precomp_dippinglayer.m)

Should these files remain as is, or should I add the link to the `sws_tools` GitHub repository and your ORCID?

**Comment by yvonnefroehlich** [comment]
@michaelgrund from my side this PR should be finished, except the https://github.com/michaelgrund/sws_tools/pull/8#issuecomment-1424742906.

**Comment by michaelgrund** [comment]
> > > This PR aims to fix typos in the docs and comments.
> > > @michaelgrund should your KIT email address be replaced by the link to the `sws_tools` GitHub repository and/or your ORCID?
> > 
> > 
> > That would be nice @yvonnefroehlich wink .
> 
> Sure, happy to help (a bit) slightly_smiling_face. I changed all occurrences. However, there are some files which do not contain any reference:
> 
>     * [`plot_arc3D.m`](https://github.com/michaelgrund/sws_tools/blob/main/01_stereoplots/plot_arc3D.m)
> 
>     * [`SWS_Analysis_BASICS_check_matlab_version.m`](https://github.com/michaelgrund/sws_tools/blob/main/01_stereoplots/SWS_Analysis_BASICS_check_matlab_version.m)
> 
>     * [`SWS_modeling_check_matlab_version.m`](https://github.com/michaelgrund/sws_tools/blob/main/01_stereoplots/SWS_Analysis_BASICS_check_matlab_version.m)
> 
>     * [`SWS_modeling_precomp_single_layer.m`](https://github.com/michaelgrund/sws_tools/blob/main/03_modeling/SWS_modeling_precomp_single_layer.m)
> 
>     * [`SWS_modeling_calc_dipping.m`](https://github.com/michaelgrund/sws_tools/blob/main/03_modeling/SWS_modeling_precomp_dippinglayer.m)
> 
> 
> Should these files remain as is, or should I add the link to the `sws_tools` GitHub repository and your ORCID?

From my side it's fine as is.

**Review by michaelgrund — APPROVED** [review]

**Pull request merged**
